# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TQUICTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TQUICTest
  pod 'OpenSSL-Universal',:git => 'https://gitee.com/jjguodong_520/open-ssl-universal'

end
