# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'CurlTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurlTest
  pod 'SwiftyCurl'
  
  target 'CurlTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurlTestUITests' do
    # Pods for testing
  end

end
