# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

source 'https://github.com/aliyun/aliyun-specs.git'


target 'EMASCurlTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'EMASCurl', '1.2.0-beta'

  # Pods for EMASCurlTest

  target 'EMASCurlTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EMASCurlTestUITests' do
    # Pods for testing
  end

end
